### PR TITLE
Use lowercase hex values and numeric font-weight values.

### PR DESCRIPTION
**Pull request by XhmikosR**
This improves compression a bit.

This could be enforced with a linter, but I'm not very familiar with JSX/React. Happy to help with the rules, though.

### CODE REVIEW

**Comment by styfle** [comment]
What's the size before and after this change? Do you have a tool to compare the compression?

**Comment by XhmikosR** [comment]
Using curl or the browser's network tools :)

**Comment by XhmikosR** [comment]
If you deploy it, we could get a before after comparison. I don't expect it to be big, just squashing some bytes with trivial changes.

Ideally, all CSS should be moved in head and compressed, but that's something I can't provide a patch for myself. Just an idea for you later :)

**Comment by XhmikosR** [comment]
OK the comparison with staging isn't clear; something is causing different sizes on staging.

That being said, this should definitely not hurt compression. Worst case, it would be the same.

**Comment by styfle** [comment]
Chome Dev Tools shows both before and after as 8.4KB

https://packagephobia-br9ucdlim.now.sh/result?p=tape

**Comment by styfle** [comment]
I count 6 bytes smaller.

I like uppercase hexadecimal colors better and I like `black` instead of `#000` so I'm going to close this PR.

**Comment by XhmikosR** [comment]
You should compare the results page, but anyway, this won't have any big impact.

It boils down to a personal preference and if a minifier is used all this is moot.

**Comment by styfle** [comment]
ZEIT Now uses brotli to compress the response when the client supports it so adding an Accepts br header should show the actual change in size.

**Pull request closed without merging**
