### PR TITLE
Increase timeout to 3 minutes

### LINKED ISSUE #444: Error 500 with some packages
We must hit a timeout or something, but whenever I try https://packagephobia.now.sh/result?p=critical@1.3.2 I git Error 500

Not sure how to solve this. I mean, you could increase the process timeout, but then it might affect the whole site performance.

### PR DESCRIPTION
**Pull request by styfle**
Fixes #444

### CODE REVIEW

**Comment by XhmikosR** [comment]
It seems the issue still happens with https://packagephobia-git-timeout-3m.styfle.now.sh/result?p=critical@0.9.0 and https://packagephobia-git-timeout-3m.styfle.now.sh/result?p=critical@0.9.1 that I tried.

But it doesn't seem to take 3 minutes before I receive the error; it seems it's way less.

**Comment by styfle** [comment]
Here's the full error:

```
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
2019-11-13T16:32:36.793Z	bd9347b1-a02d-4b12-99a8-b1308fcef909	INFO	
> phantomjs-prebuilt@2.1.16 install /tmp/tmp-package0.817794128287934/node_modules/phantomjs-prebuilt
> node install.js
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Received 22866K total.
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { Error: spawn tar ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn tar',
  path: 'tar',
  spawnargs:
   [ 'jxf', '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2' ],
  cmd:
   'tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2' } Error: spawn tar ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm WARN notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"10.17.0","npm":"6.13.0"})
npm WARN notsup Not compatible with your version of node/npm: got@5.7.1
2019-11-13T16:32:37.699Z	bd9347b1-a02d-4b12-99a8-b1308fcef909	ERROR	undefined
2019-11-13T16:32:37.710Z	bd9347b1-a02d-4b12-99a8-b1308fcef909	ERROR	ERROR: phantomjs-prebuilt@2.1.16 install: `node install.js`
Exit status 1
```

**Comment by XhmikosR** [comment]
Hmm alright so the increase in timeout is moot :)

There issue is the npm version used to install a package. IIRC yarn does have an option to ignore the engines version, but I can't find anything similar for npm.

You can close the patch and maybe reopen #444 and I'll add more info there.

**Comment by XhmikosR** [comment]
BTW I don't get the tar error. Doesn't the host machine have tar available?

**Comment by styfle** [comment]
I see, its trying to spawn `tar` from the command line which doesn't exist. The probably used `node-tar` which is why it works for newer versions.

**Comment by XhmikosR** [comment]
Still the issue with packages limiting the maximum npm or even node version can happen. I still don't think there's a way to ignore engines with npm, so this will definitely keep happening.

**Pull request closed without merging**
