### PR TITLE
Upgrade to now v2

### PR DESCRIPTION
**Pull request by styfle**
This is my first attempt to get Package Phobia running on Now v2

### CODE REVIEW

**Comment by styfle** [comment]
Related issue:

https://github.com/stelligent/dromedary-serverless/issues/3

The solution seems to be adding the `HOME` environment variable in [748e7de](https://github.com/stelligent/dromedary-serverless/commit/748e7dead2fec3a60475645d038cc0c536f11b21).

**Comment by r0mflip** [comment]
Are you trying to use `ts` files directly unlike in Now 1.0 where they were compiled?

**Comment by styfle** [comment]
With Now 2.0 builders, the entry point to the builder can be TypeScript and it will perform the compilation and actually bundle all the code into a lamda. 

The problem I’m running into is that the bundle does not include the CLI so I can’t spawn a child process to invoke npm install.

**Comment by r0mflip** [comment]
I think you can try using `@now/static-build` instead of making it into a lambda if it won't let you fork processes. Just compile the `ts` and run it.

**Comment by styfle** [comment]
@r0mflip If you think you can fix it, feel free to create a PR 😁

I’m pretty certain I can’t use a static builder because this is not a static website. 

At best, I could use the node-server builder but I would like to wait for feedback on this ncc bug: https://github.com/zeit/ncc/issues/275

**Comment by r0mflip** [comment]
@styfle Yeah, you are right, I'am wrong about that.

**Comment by styfle** [comment]
@r0mflip You can build a traditional server. See https://github.com/styfle/react-server-example-tsx for an example that was just upgrade to Now 2.0

The thing to remember is that "traditional" servers have the assumption that they can take as long as necessary to boot because it only happens once. But serverless favors many smaller, faster booting microservices so it can be scaled out on-the-fly as traffic increases (or scaled down when traffic decreases).

Now 2.0 pushes you (the developer) towards this serverless architecture.

**Comment by r0mflip** [comment]
Each route becomes an isolated microservice right.

**Comment by styfle** [comment]
Ideally, yes

**Comment by styfle** [comment]
LET'S DO THIS! :shipit: 🚀

**Pull request merged**
