### PR TITLE
Add preconnect meta tag

### LINKED ISSUE #443: Add `dns-prefetch` for badgen.net in results page
Should improve slightly the results page load time

### PR DESCRIPTION
**Pull request by styfle**
Fixes #443 using [preconnect](https://developers.google.com/web/fundamentals/performance/resource-prioritization#preconnect).

### CODE REVIEW

**Comment by XhmikosR** [comment]
Personally, I wouldn't use preconnect here. I'd start with dns-prefetch and see how it goes, because badgen is very slow and this will slow down the initial page load time.

**Comment by styfle** [comment]
@XhmikosR What makes you think https://badgen.net is slow? Its also hosted on ZEIT Now.

```sh
$ time curl https://badgen.net
real	0m0.229s
user	0m0.026s
sys	0m0.015s

$ time curl https://packagephobia.now.sh
real	0m0.230s
user	0m0.022s
sys	0m0.011s

$ time curl https://packagephobia-ffwkzpf9j.now.sh # old deployment
real	0m0.373s
user	0m0.023s
sys	0m0.015s
```

**Comment by XhmikosR** [comment]
It might be fast where you are but not here

https://gtmetrix.com/compare/bJY5cQYb/NSIx2HwV#waterfall

**Comment by amio** [comment]
> I'd start with dns-prefetch and see how it goes, because badgen is very slow and this will slow down the initial page load time.

@XhmikosR Sorry to hear that. Performance is definitely in Badgen's top list, we will fix it 💪

**Pull request merged**
